<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\ReceitasPerfeitas.Communication\ReceitasPerfeitas.Communication.csproj" />
    <ProjectReference Include="..\..\Shared\ReceitasPerfeitas.Exceptions\ReceitasPerfeitas.Exceptions.csproj" />
    <ProjectReference Include="..\ReceitasPerfeitas.Application\ReceitasPerfeitas.Application.csproj" />
  </ItemGroup>

</Project>
